name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: "ilariae"
          outputs: "github-contribution-grid-snake.svg"
      - uses: actions/upload-artifact@v3
        with:
          name: snake-game
          path: github-contribution-grid-snake.svg
      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
